name: CI

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.repository == 'openupm/openupm-website-cn'
    steps:
    - name: deploy website
      uses: maddox/actions/ssh@master
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST: ${{ secrets.HOST_CN }}
        USER: ${{ secrets.USER }}
      with:
        args: |
            /home/openupm/openupm-devops/scripts/deploy-website-cn.sh
